-- Auto-generated from schema-map-postgres.yaml (map@sha1:8C4F2BC1C4D22EE71E27B5A7968C71E32D8D884D)
-- engine: postgres
-- table:  magic_links

CREATE TABLE IF NOT EXISTS magic_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fingerprint CHAR(64) NOT NULL,
  subject VARCHAR(128) NOT NULL,
  user_id BIGINT NULL,
  context JSONB NULL,
  expires_at TIMESTAMPTZ(6) NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT ux_magic_links_fingerprint UNIQUE (fingerprint)
);
